### ISSUE TITLE
Solution to monitor EdgeDB instance

### ISSUE THREAD

**Issue by Jarrodsz** [IgnisDa/dokku-edgedb#10]
Here a short proposal for a way to enable monitoring for EdgeDB.

https://www.edgedb.com/docs/guides/deployment/health_checks#ref-guide-deployment-health-checks

Perhaps there could be some easy way to enable monitoring and integrate with an opensource solution like:
https://novu.co
or other push notification implementation so you recieve a warning when there are problems with the edgedb instance. 

Not sure if this is a good proposal but it seems to be the only missing thing to make this perfect.
Perhaps Its outside of the scope of the plugin but thought I share this final thought.

**Comment by IgnisDa** [comment]
I'd say this is not in the scope of this plugin as well as i said in my comment on #11. Everything I said there applies here too.
