### ISSUE TITLE
Extend backup solution with locale filestorage

### ISSUE THREAD

**Issue by Jarrodsz** [IgnisDa/dokku-edgedb#11]
If im correct reading the docs currently only S3 backups are possible?

A proposal to extend the backup feature with 2 small additions.

1. Local storage on the server where dokku runs on ( outside the container ) encrypted.
2. Option to use SCP to copy database backup securely to a remote file server.

**Comment by IgnisDa** [comment]
I don't think this should be supported in the core plugin. I want to keep this plugin feature parallel with the other Dokku official plugins. However, since plugins are just bash scripts, you can write one out and I'll be glad to include it on the repository wiki.
