### ISSUE TITLE
Would this plugin also work for nightly build version of edgedb?

### ISSUE THREAD

**Issue by Jarrodsz** [IgnisDa/dokku-edgedb#4]
Firstmost thank you very much for creating this plugin,
is it considered stable enough to use in a simple MVP application on production for now?

Im testing the nightly build of edgedb, and wonder if this works or i have to specify the nighty build when creating a new instance of edgedb with this plugin.

**Comment by IgnisDa** [comment]
I am using it for a few personal projects of mine and have not encountered any major issues. If you are willing to take the risk, you can use it in production. If any issue arises, you can open a ticket here, and I will help you the best I can.

Thanks for using it! :)

**Comment by IgnisDa** [comment]
Technically it can support more than one instance each service but the plugin does not support this directly. We can discuss it if you need this feature.
